プレートの判定処理修正
amataku/key-notify-hard pull request #12
Opened 2018-12-14 11:45 UTC by equanz

2018-12-14 11:47 UTC, equanz commented
状態遷移をきちんと捉える必要がありそうです．
しっかりレビュー願います．

2018-12-15 03:28 UTC, amataku requested changes
論理のバグ修正&コードの修正ありがとうございます。
一点気になる点があったので確認をお願いします。

2018-12-15 03:28 UTC, amataku commented on notify.py
> +    plate_state = int(bool(input_1) and bool(input_2))
* この部分はOR演算が適切ではないでしょうか

2018-12-15 04:38 UTC, equanz commented on notify.py
> +    plate_state = int(bool(input_1) and bool(input_2))
inputが 1 のときOFFという認識でいいですか?

だとすると，両方のinputが 1 のとき，plate_stateは 1 となる条件は，
input_1 and input_2 で満たしていると思います．

間違っていたら教えてください．

2018-12-15 08:45 UTC, amataku commented on notify.py
> +    plate_state = int(bool(input_1) and bool(input_2))
確認しました
問題ないです

2018-12-15 08:46 UTC, amataku approved these changes
修正ありがとうございます

2018-12-15 08:49 UTC, merged