機能の追加
amataku/key-notify-hard pull request #13
Opened 2019-01-29 04:57 UTC by amataku

## やったこと
* 鍵がある時LEDが光る機能(回路作成の必要あり)
* ネットワークエラーとステータスコードをログに残す機能
* 再起動時にgitリモートとの同期

## やってないこと
* 特になし

2019-01-29 06:25 UTC, equanz requested changes
質問・修正点を挙げています．
確認ください．

2019-01-29 06:25 UTC, equanz commented on notify.py
> +                    log.debug(req.status_code)
finallyにreq.status_codeを配するのは良くなさそうです．
なぜならば，reqに代入すべきオブジェクトを生成する `sessin.post()` 以前がtry内で例外を起こした場合 reqには何も代入されていないことになるからです．

ちなみにいうと，finallyはtry中に例外が発生したかどうかにかかわらず(つまりexceptを通った後だとしても)実行されます．

https://docs.python.jp/3/tutorial/errors.html#defining-clean-up-actions

2019-01-29 06:25 UTC, equanz commented on notify.py
> +                    req = session.post(url,data = json.dumps(payload),timeout = TIMEOUT,headers = headers)
私もPythonをきっちり勉強していなかったので恥ずかしい限りですが，このreq はPythonのスコープとしては問題ないようですね．
Pythonはブロックスコープというわけではないようです．

https://docs.python.jp/3/tutorial/classes.html#python-scopes-and-namespaces

2019-01-29 06:25 UTC, equanz commented on notify.py
> +                    GPIO.output(OUTPUT_CHANNEL, True)
ここは議論が分かれると思うので相談です．
finally句に置くということはプログラムにおける内部状態が変わったかどうかを表示するLEDであることを指しています．これは意図した挙動ですか? それとも本当はきちんとSlackに通知を送信する(厳密にはサーバにPOSTする)事ができたかどうかを表示しようと考えていますか?

(ちなみに私はIoT機器の状態を示すLEDという認識なのでこの挙動で良いと思っています．)

2019-01-29 06:25 UTC, equanz commented on notify.py
> +log  = logger.logger('key_notify hard')
この行はloggerオブジェクトのloggerメソッドを実行している(もしくは単にloggerパッケージのlogger関数を実行?)ようですがloggerオブジェクト(もしくはloggerパッケージ?)はどこに宣言されていますか?
参照元等あればご教示ください．

2019-01-29 06:25 UTC, equanz commented on start_notify.sh
> +git -C /home/pi/key-notify-hard pull origin master
`-C` オプションがあるんですね．これはカレントディレクトリに対する依存がなく，良い処理かと思います．

2019-01-29 06:32 UTC, equanz commented on notify.py
> +                    log.debug(req.status_code)
具体的には，Timeoutのとき例外が起こるようですね．

http://jp.python-requests.org/en/latest/user/quickstart/#timeouts

2019-01-29 06:38 UTC, amataku commented on notify.py
> +                    log.debug(req.status_code)
ではステータスコードのログ出力はなくて大丈夫ですか

2019-01-29 06:41 UTC, amataku commented on notify.py
> +                    GPIO.output(OUTPUT_CHANNEL, True)
このLEDはデバッグ用に使用するものだと考えているので、通知が来なかったときハード側が正常に動作しているか確認するためには、これが良いかなと思いました

2019-01-29 06:41 UTC, amataku commented on notify.py
> +                    req = session.post(url,data = json.dumps(payload),timeout = TIMEOUT,headers = headers)
無知なのでよく考えず書きました

2019-01-29 06:42 UTC, equanz commented on notify.py
> +                    log.debug(req.status_code)
いや，404とかのステータスコードエラーを拾う方法が現時点ではサーバ側からしか無いのであったほうが嬉しい．
ここは，新たにelseを使ってexceptでないときのみ実行するようにしてはどうだろう．

もちろん，これ以降の処理(特にL:118)をelseにおくか，finallyに置くか検討する必要はあると思うが．

2019-01-29 06:43 UTC, equanz commented on notify.py
> +                    GPIO.output(OUTPUT_CHANNEL, True)
見解が一致していますね．
じゃあ，このまま行きましょう． 👍

2019-01-29 06:46 UTC, amataku commented on notify.py
> +                    log.debug(req.status_code)
そうしておきます

2019-01-29 06:51 UTC, amataku commented on notify.py
> +log  = logger.logger('key_notify hard')
修正しました

2019-01-29 06:51 UTC, amataku commented on notify.py
> +                    GPIO.output(OUTPUT_CHANNEL, True)
はい

2019-01-29 06:55 UTC, equanz requested changes
確認漏れがあったので再度．

2019-01-29 06:55 UTC, equanz commented on notify.py
> +        def debug(self, msg):
見落としかもしれないので一応確認まで，
debug, info, ... のメソッドはLoggerクラスのコンストラクタ(ここでは __init__ メソッド)の内部で宣言されていますが意図的なものですか?

2019-01-29 07:00 UTC, amataku commented on notify.py
> +        def debug(self, msg):
修正しました
間違っていると考えられるものには、間違っているのではないかと言っていただけると幸いです

2019-01-29 07:03 UTC, equanz commented on notify.py
> +        def debug(self, msg):
レビューが嫌味っぽく見えて申し訳ない．
本当にこのような宣言があるのか断言できるほどPython詳しくないのでこのようなコメントをしています．

修正確認しました． 👍

2019-01-29 07:03 UTC, equanz approved these changes

2019-02-01 15:40 UTC, equanz commented
そういえばGPIOピンの設計図を書き直していないと思います．
このPRに含めるのが妥当かなと思うのですがどうですか？

2019-03-04 15:56 UTC, merged